import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import Providers from './providers';
import Header from './components/layout/Header';
import { SearchProvider } from './_contexts/SearchContext';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-gray-100">
        <Providers>
          <SearchProvider>
            <Header />
            {children}
          </SearchProvider>
        </Providers>
      </body>
    </html>
  );
}
